
NON_CORE_DEPDENDENT_TASKS_FIRST_PRIORITY = 9999

# MessageProcessor
# priority constants for message processors between modules
ASSETS_PRIORITY_PARSE_ISSUANCE = NON_CORE_DEPDENDENT_TASKS_FIRST_PRIORITY - 0
ASSETS_PRIORITY_PARSE_DESTRUCTION = NON_CORE_DEPDENDENT_TASKS_FIRST_PRIORITY - 1
ASSETS_PRIORITY_BALANCE_CHANGE = NON_CORE_DEPDENDENT_TASKS_FIRST_PRIORITY - 2
DEX_PRIORITY_PARSE_TRADEBOOK = NON_CORE_DEPDENDENT_TASKS_FIRST_PRIORITY - 3
BETTING_PRIORITY_PARSE_BROADCAST = NON_CORE_DEPDENDENT_TASKS_FIRST_PRIORITY - 4
CWALLET_PRIORITY_PARSE_FOR_SOCKETIO = NON_CORE_DEPDENDENT_TASKS_FIRST_PRIORITY - 5  # comes last

# MempoolMessageProcessor
CWALLET_PRIORITY_PUBLISH_MEMPOOL = NON_CORE_DEPDENDENT_TASKS_FIRST_PRIORITY - 0